---
kr_config_base: /home/vagrant/support/base
kr_base_script: "{{ kr_src_dir }}/utils/layer0/build-layer0-base.sh"
kr_kmod_script: "{{ kr_src_dir }}/utils/layer0/build-layer0-kmod.sh"
kr_config_script: "{{ kr_src_dir }}/utils/layer0/build-layer0-config.sh"

kr_kmod_all: false
# this is the module set for vbox vms
kr_kmod_modules:
  - ac97_bus
  - acpi-cpufreq
  - e1000
  - i2c-piix4
  - intel_pmc_core
  - serio_raw
  - snd
  - snd-ac97-codec
  - snd-intel8x0
  - snd-pcm
  - snd-pcsp
  - snd-timer
  - soundcore
  - video
  - rbd
  - overlay
  - squashfs
