---
- name: Get running kernel version
  command: uname -r
  register: kern_out
  changed_when: false

- name: Set kernel facts
  set_fact:
    mod_dir: "/lib/modules/{{ kern_out.stdout }}"
    kernel_file: "vmlinuz-{{ kern_out.stdout }}"
    kr_tftp_dir: "{{ kr_tftp_base }}/amd64/{{ kr_platform }}"

- debug:
    msg: >
      Kernel module directory is: {{ mod_dir }}, kernel is: {{ kernel_file }}

- name: Create TFTP directory
  file:
    path: "{{ kr_tftp_dir }}"
    state: directory
    mode: 0755

- debug:
    msg: "TFTP directory is {{ kr_tftp_dir }}"

- name: Install syslinux-tftpboot
  become: true
  package:
    name: syslinux-tftpboot
    state: present

- name: Copy tftpboot files
  synchronize:
    src: "{{ syslinux_tftpboot }}/"
    dest: "{{ kr_tftp_dir }}"
  delegate_to: "{{ inventory_hostname }}"

- name: Copy kernel to TFTP directory
  copy:
    src: "/boot/{{ kernel_file }}"
    dest: "{{ kr_tftp_dir }}/{{ kernel_file }}"
    mode: 0644
    remote_src: true

- name: Write pxelinux.cfg to TFTP directory
  template:
    src: default.tpl.j2
    dest: "{{ kr_tftp_dir }}/pxelinux.cfg"
    mode: 0644
